container:
  image: node:10.15.1
  additional_containers:
    - name: rethinkdb
      image: rethinkdb:2.3.6
      port: 21085

lint_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  test_script: yarn lint

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  test_script: yarn test
