version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.29
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: 'mongodb://localhost:27017/yunsheDev'
  prisma_test:
    image: prismagraphql/prisma:1.29
    restart: always
    ports:
    - "4477:4477"
    environment:
      PRISMA_CONFIG: |
        port: 4477
        databases:
          default:
            connector: mongo
            uri: 'mongodb://localhost:27017/yunsheTest'